
```{r methods-data, include=FALSE}
fp <- here("analysis", "data", "derived_data", "mids_rf.rds")
mids_rf <- readr::read_rds(fp)
```

### Animals
Female Sprague-Dawley rats aged 10-12 weeks (220-250 g) at the start of the experiment were used in this study. Rats were grouped-housed in standard polycarbonate cages on a 12 h light-dark cycle (lights on 08:00-20:00), standard temperature (22 ± 2`r knitr::asis_output("\u00B0C")`) and humidity (40-55%) with food and water available _ad libitum_. Experiments were approved by the Ethical Committee for Animal Experiments of the Estonian Ministry of Rural Affairs (permission 25.06.2018 nr. 127) in accordance with Directive 2010/63/EU of the European Union.

### Drugs
Racemic ketamine (Bioketan, Vetoquinol Biowet, Gorzów Wielkopolski, Poland) diluted in sterile saline was administered intraperitoneally at a dose of 30 mg/kg and an injection volume of 1 ml/kg once per day for 10 consecutive days. Control animals received saline at 1 ml/kg.

### Tissue Collection
Brains were collected 24h after the last injection and flash frozen in isopentane on dry ice followed by storage at -80`r knitr::asis_output("\u00B0C")`. Sections of 40 µm were sliced on a Leica CM1520 cryostat onto VWR Superfrost Plus slides and stored at -80`r knitr::asis_output("\u00B0C")` until use. 

### Cytochrome C oxidase staining and image analysis
Cytochrome C oxidase staining and image analysis were performed as described in Kanarik and Harro [-@kanarikSociabilityTraitRegional2018], based on a modified protocol by Gonzalez-Lima and Cada [-@gonzalez-limaQuantitativeHistochemistryCytochrome1998]. Coronal brain sections were pre-incubated for 10 min with 0.0275% cobalt chloride (w/v) and 0.5% dimethyl sulphoxide (v/v) in 0.05 M Tris buffer with 10% sucrose (w/v) adjusted to pH to 7.4 with 0.1% HCl (v/v). The sections were then incubated for one hour at room temperature in a solution consisting of 0.05% 3,3′-diaminobenzidine tetrahydrochloride (AppliChem), 0.0075% cytochrome c (Sigma), 5% sucrose, 0.002% catalase (Sigma) and 0.25% dimethyl sulphoxide (v/v) in sodium phosphate buffer (pH 7.4). Image analysis was conducted using the Image J 1.34 s freeware on the blue channel (resulting from a RGB split) of the background subtracted image. Brain regions were detected from the stained images according to the rat brain atlas [@paxinosRatBrainStereotaxic2007]. Enzyme activity levels were derived from optical density measurements of a histochemical reaction product within each brain region. The optical density values were converted to enzyme activity levels by using external standardisation: Sections made of brain homogenate with spectrophotometrically measured enzyme activity were included in all incubation baths.

## Statistical analysis
### Data imputation
Raw data contained COX measurements for 247 brain regions in 14 rats. Seven animals were from the control and 7 from the treatment group, respectively. For 69 brain regions, the data were complete. In some cases the planned measurements were not attainable owing to cutting-induced defects or shift of the cut on the rostral-caudal axis, leading to missing measurements for 1 or more animals. Multiple imputation of the missing data was performed. Because the original data had a significant number of highly correlated variables, we used random forest approach to deal with the multicollinearity. This model was applied to brain regions with 2 or fewer missing cases in each experimental condition. There were 121 such brain regions. In total 190 brain regions were included in subsequent analyses. The rest of the data were discarded. Ten multiply imputed datasets were generated by R-package *mice* [@R-mice]. The implementation of Breiman's [-@breimanClassificationRegressionTrees1984] random forest algorithm for R language was used as described by Doove and colleagues [-@dooveRecursivePartitioningMissing2014]. The algorithm was run for 20 iterations and showed good convergence. An example of the imputed data for one of the brain regions is shown on Figure 1 in Supplementary materials.

### Testing for difference in mean COX levels
We applied Welch's two sample t-test to the 10 imputed datasets and used Barnard-Rubin's method to adjust the degrees of freedom for small samples in pooled data [@barnardMiscellaneaSmallsampleDegrees1999]. 

### Differential correlation analysis
We employed the Differential Correlation Analysis (DCA) to identify the brain regions with different correlation profiles in control and ketamine group rats. Spearman rank-order correlation coefficients were calculated between all possible pairs of brain regions in each of the 10 multiply imputed data sets. Spearman's method was chosen because of the risk that just 1 outlier can significantly bias the correlation coefficients in small samples. Spearman's method works with ranks of the raw data, therefore on small samples it can overrepresent the true strength of the linear relationship between two variables (e.g. producing correlation coefficients close to 1). The correlation coefficients were then converted to Fisher z-scores that follow normal distribution. Finally, the difference in z-scores between two conditions (`r knitr::asis_output("\u0394 z-score)")` was calculated and the significance of the difference score evaluated separately by 1000 permutation tests in each imputed data set. The empirical p-values from the permutation tests were then averaged across the 10 multiply imputed data sets. The medians of z-scores were calculated in a similar manner. Besides pairwise correlations, the median change in correlation for each brain region with all others (gives 1 summary score for each brain region) and the median change in correlation between two conditions across all brain regions (provides 1 summary score) were also calculated. The DCA procedures were carried with DGCA R software package [@mckenzieDGCAComprehensivePackage2016].

### Significance thresholds
The statistical significance threshold for t-tests and median regional change in correlations in DCA is set at p level of 0.05. Pairwise DCA analysis involved 17,955 separate comparisons of correlation z-scores between two conditions. It was important to strike a reasonable balance between scientific discovery and the risk of significance due to chance. Therefore, in the main text the statistical significance threshold is set at p level of 0.01. Additionally, only brain regions with at least two pairwise significant changes in correlation coefficients between conditions are included in the main text. Full results of pairwise DCA at significance level p = 0.05 are presented as a heatmap on Figure 2 in Supplementary materials. 
