---
title             : "Cytochrome c oxidase metabolic mapping in a chronic ketamine administration model"
shorttitle        : "cytochrome oxidase after chronic ketamine"
author:
  - name          : "Denis Matrov"
    affiliation   : "1,3"
  - name          : "Sophie Imbeault"
    affiliation   : "2"
  - name          : "Margus Kanarik"
    affiliation   : "3"
  - name          : "Marianna Shkolnaya"
    affiliation   : "2"
  - name          : "Patricia Schikorra"
    affiliation   : "2"
  - name          : "Ergo Miljan"
    affiliation   : "2"
  - name          : "Ruth Shimmo"
    affiliation   : "2"
  - name          : "Jaanus Harro"
    affiliation   : "3"  
    corresponding : yes
    address       : "Postal address"
    email         : "jaanus.harro@ut.ee"

affiliation:
  - id            : "1"
    institution   : "Department of Neuroscience, Graduate School of Medicine, Kyoto University, Kyoto, Japan"
  - id            : "2" 
    institution   : "Tallinn University Centre of Excellence in Neural and Behavioural Sciences, School of Natural Sciences and Health, Tallinn University, Tallinn, Estonia" 
  - id            : "3"
    institution   :  "Division of Neuropsychopharmacology, Department of Psychology, University of Tartu, Tartu, Estonia"
    
keywords          : ["rats", "cytochrome oxidase", "ketamine"]
wordcount         : "X"

bibliography      : ["references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
csl               : "../templates/behavioural-brain-research.csl"
output            : papaja::apa6_pdf
---

```{r setup, echo = FALSE, include = FALSE, cache=FALSE}
library("papaja")
library("ggplot2")
library("tidyverse")
library("scales")
library("gridExtra")
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(
  cache = TRUE,
  cache.comments = FALSE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  echo = FALSE,
  strip.white = TRUE,
  comment = "#>",
  fig.path = "../figures/",
  results = "asis",
  tidy = "styler",
  dev = c('pdf', 'tiff'),
  dev.args = list(pdf = list(colormodel = 'cmyk'), 
                  tiff = list(compression = 'lzw')),
  dpi = 600,
  fig.width = 7,
  fig.height = 7,
  concordance = TRUE,
  global.par = TRUE
)

par(font.main = 1, cex.main = 1.05)
theme_set(theme_apa(base_size = 15) + theme(legend.position = "bottom"))
```



<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

# Introduction

Here is a citation

# Background


# Methods

```{r include-methods, child = "02-methods.Rmd"}
```



# Results

```{r include-results, child = "03-results.Rmd"}
```


# Discussion

# Conclusion

# Acknowledgements

<!-- The following line inserts a page break when the output is MS Word. For page breaks in PDF, use \newpage on its own line.  -->

\pagebreak

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

\pagebreak

